env: "local"

http_server:
  address: "0.0.0.0:8080"
  timeout: "10s"
  idle_timeout: "60s"
  user: "${HTTP_USER}"
  password: "${HTTP_PASSWORD}"

database:
  host: "${DB_HOST}"
  port: "${DB_PORT}"

  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  dbname: "${DB_NAME}"
  sslmode: "disable"

# kafka: 
#   address: "${KAFKA_ADDRESS}"
#   topic: "${TOPIC}"
#   group: "${GROUP}"

kafka: 
  address: "localhost:9092"
  topic: "wb-tech-topic"
  group: "wb-tech-consumer-group"

migrations:
  dir: "./migrations"
  table: "schema_migrations"

redis:
host: "${REDIS_HOST}"
port: "${REDIS_PORT}"
password: "${REDIS_PASSWORD}"
db: ${REDIS_DB}