env: "local"

http_server:
  address: "127.0.0.1:8001"
  timeout: "10s"
  idle_timeout: "60s"
  user: "${HTTP_USER}"
  password: "${HTTP_PASSWORD}"

database:
  host: "${DB_HOST}"
  port: "${DB_PORT}"

  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  dbname: "${DB_NAME}"
  sslmode: "disable"

kafka: 
  address: "kafka:29092"
  topic: "wb-tech-topic"
  group: "wb-tech-consumer-group"

migrations:
  dir: "./migrations"
  table: "schema_migrations"

redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0